name: PHP Web CI

on:
  push:
    tags:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub 
      uses: docker/login-action@v3 
      with:
          username: valerian.charrier@gmail.com
          password: 8v42O@576

    - name: Build Docker Image
      run: docker build -t my-ping-app ./ping # Assurez-vous que ce chemin est correct
    
    - name: Run Docker Container
      run: docker run -d --name my-ping-container my-ping-app
    
    - name: Ping Command
      run: docker exec my-ping-container curl localhost:8080 # Remplacez example.com par l'adresse que vous souhaitez pinger

    - name: Stop and Remove Container
      run: docker stop my-ping-container && docker rm my-ping-container